### ISSUE TITLE
Better generation of enum variants?

### ISSUE THREAD

**Issue by Skippeh** [dbeckwith/rust-typescript-type-def#21]
At the moment externally tagged (and possibly other) enum variants are generated as unions. But this makes them very annoying to handle in typescript.

Consider the following rust enum:

```rust
enum MyEnum {
    A { a: i32 },
    B { b: String },
}
```

The following typescript would be generated:

```typescript
type MyEnum = {
    a: {
        a: number;
    };
} | {
    b: {
        b: string;
    };
}
```

This output makes it impossible to refer to any of the fields unless you use a separate struct type for each variant.

Is it possible to have an option to make it generate the following (or something similar) instead?

```typescript
type MyEnum = {
  a?: {
    a: number;
  };
  b?: {
    b: string;
  };
};
```

The typescript examples are slightly wrong for brevity but i hope my point is conveyed none the less.

**Comment by dbeckwith** [comment]
This library generates Typescript types which align with Serde's serialization of Rust values into JSON, so it all comes down to how you configure Serde. [Serde's documentation](https://serde.rs/enum-representations.html) describes multiple ways you can get it to encode enums. The default enum representation is "externally tagged" which generates the form you're describing and I agree can be a bit annoying to work with. The other representations are more amenable to accessing common fields, so I would recommend trying them out.

About changing the type generation, I think it's important for the TS types generated by this library to describe the form of the data as precisely as possible, and your second example allows for values which are not valid for the `MyEnum` Rust type (such as `{}` and `{ a: { a: 1 }, b: { b: 'b' } }`). So I'm reluctant to change the way the types are generated. I think picking a different enum representation should accomplish what you're after.

**Comment by Skippeh** [comment]
None of the other representations work either because they all eventually become unions for the actual value variants.

It's true that my example would allow for invalid values, but is it possible they would fail deserialisation on the rust side anyway?

Maybe there's a better representation possible.

**Comment by dbeckwith** [comment]
Maybe I'm not fully understanding what you're trying to do, can you elaborate on this?

> This output makes it impossible to refer to any of the fields unless you use a separate struct type for each variant.

Can you give an example of some TS code you would like to use that doesn't work?

**Comment by Skippeh** [comment]
I have this struct:

```rust
#[derive(Debug, Serialize, TypeDef, Clone)]
#[serde(rename_all = "camelCase")]
pub enum CheckAuthResponse {
    #[serde(rename_all = "camelCase")]
    Success {
        name: String,
        avatar_url: String,
        auth_token: String,
    },
    Failure {
        error: String,
    },
}
```

Which generates the following ts:

```typescript
export type CheckAuthResponse=({"success":{"name":string;"avatarUrl":string;"authToken":string;};}|{"failure":{"error":string;};});
```

Trying to access ```response.success``` or ```success.failure``` results in a transpiler error, complaining that the property doesn't exist on all union variants.

I could do the following to test if something isn't undefined:

```typescript
if ("success" in response) { ... }
```

It's potentially hard to find usages though, and changing names or removing fields. It's also prone to runtime errors with typos.

**Comment by dbeckwith** [comment]
I've written a lot of Typescript for work, and I've found that the pattern you're describing of having unions of objects and then [_narrowing_](https://www.typescriptlang.org/docs/handbook/2/narrowing.html) the types using guards like `if ("success" in response)` is very typical Typescript. This is generally how you're meant to use Typescript's type-system; its job is to enforce correctness by making you check if fields actually exist before using them. The types are saying "the `avatarUrl` field will _only_ be defined if the `type` field is `"success"`", so you _have_ to check that condition before you can access that field.

For what it's worth, if you don't like using the `in` operator, I think the pattern works a bit better using Serde's tagged enum format:

```rust
#[derive(Debug, Serialize, TypeDef, Clone)]
#[serde(rename_all = "camelCase", tag = "type")]
pub enum CheckAuthResponse {
    #[serde(rename_all = "camelCase")]
    Success {
        name: String,
        avatar_url: String,
        auth_token: String,
    },
    Failure {
        error: String,
    },
}
```

would generate:

```typescript
export type CheckAuthResponse = 
  | {
      "type": "success";
      "name": string;
      "avatarUrl": string;
      "authToken": string;
    }
  | {
      "type": "failure";
      "error": string;
    };
```

Then you can do:

```typescript
if (response.type === "success") { ... }
```

or even:

```typescript
switch (response.type) {
  case 'success':
    // here, response is of type { "type": "success"; "name": string; ... }
    break;
  case 'failure':
    // here, response is of type { "type": "failure"; "error": string; }
    break;
}
```

And to your comment about it being prone to typos, TS will generally produce an error or at least a warning if you do `if ("prop" in object)` but `object`'s type never has any field named `prop`.

**Comment by Skippeh** [comment]
Thank you, using a tag seems to work just fine. Sorry for wasting your time.

For some reason the "in" method doesn't warn/error about impossible values but the type tag one does.
