### ISSUE TITLE
Why field with #[serde(default)] becomes optional in TS definition?

### ISSUE THREAD

**Issue by anvlkv** [dbeckwith/rust-typescript-type-def#3]
https://github.com/dbeckwith/rust-typescript-type-def/blob/f33d1895ac003549ce61669807c85001fa69ceda/tests/test.rs#L551

Is it intentional? Is there a way to change this behavior?

```
struct S {
#[serde(default)]
field: String
}
```

the output is

```
type S = {field?: string}
```

However, default ensures there's a string so type should be {field: string}

**Comment by dbeckwith** [comment]
[`#[serde(default)]`](https://serde.rs/field-attrs.html#default) is an attribute that only affects deserialization (in other words, going from TS to Rust). In this case, it is correct because the TS value may omit the attribute, meaning it should be optional.
