### ISSUE TITLE
proc-macro-error dependency is no longer maintained.

### ISSUE THREAD

**Issue by chanks** [dbeckwith/rust-typescript-type-def#34]
Howdy! The `typescript-type-def-derive` crate has `proc-macro-error` as a dependency, which seems to be unmaintained, per [RUSTSEC-2024-0370](https://rustsec.org/advisories/RUSTSEC-2024-0370). This is causing [cargo-deny](https://github.com/EmbarkStudios/cargo-deny) to flag any workspace using `typescript-type-def` as having a security vulnerability.

[proc-macro-error2](https://crates.io/crates/proc-macro-error2) is listed as a possible alternative, but I haven't investigated how difficult it would be to migrate.

**Comment by dbeckwith** [comment]
Thanks for the report! Fixed in version 0.5.12
